name: Renovate

on:
  push:
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          renovate-version: 38.97.0
          configurationFile: renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }} # don't create PRs
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: debug
